name: Installer

on:
  push:
    branches: [master]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run PyInstaller
        run: pyinstaller --onedir --name pygfbar --add-data data/config.json:. pygfbar/cli.py
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: pygfbar-linux
          path: ./dist

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run PyInstaller
        run: pyinstaller --onedir --name pygfbar --add-data data/config.json:. pygfbar/cli.py
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: pygfbar-windows
          path: ./dist
